### ISSUE TITLE
POK-15- 🍿 Feature - feat: Add `SearchBar` UI

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/vanilla-pokedex#15]
# Adds the UI for the `SearchBar` 

![Image](https://user-images.githubusercontent.com/12022922/216775122-fde4b7a3-4760-41f8-94ed-58ef5bc8c5ed.png)

_Pictured, the `SearchBar` and various sub-elements in different states_

The `SearchBar` UI is the main form control for searching for Pokemon via the PokeAPI. This form should have a text input that can be used to search for Pokemon either by `name` or `id`. This dynamic query is controller by the `select` element which has two options: `Name` or `Id`. The final element in the search bar is the stylized `Submit` button which executes the HTTP request against the PokeAPI using the information collected via the form. 

For this story only implement the UI. We will add the actual search functionality in a separate story.

**Comment by wijohnst** [comment]
.

**Comment by mathiuskitchens** [comment]
Should the above placeholder text be changed when the different criteria is selected in the dropdown? Or is this something added later in JS?
